name: Required Approvals
on:
  pull_request:
  pull_request_review:

  workflow_dispatch:

permissions:
  checks: write
  pull-requests: read

jobs:
  check-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Check required approvals
        uses: Weetbix/configurable-required-approvals@v2.1.1
        with:
          requirements: |
            - patterns:
                - "/src/**/*"
              requiredApprovals: 1
          github-token: ${{ secrets.GITHUB_TOKEN }}

