name: Required Approvals
on:
  pull_request:
    branches:
      - main
  pull_request_review:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  check-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check required approvals
        uses: Weetbix/configurable-required-approvals@v1.0.6
        with:
          requirements: |
            - patterns:
                - "src/**/*"
              requiredApprovals: 1
          github-token: ${{ secrets.APPROVAL_GITHUB_TOKEN }}
