name: Required Approvals
on:
  pull_request:
  pull_request_review:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  check-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Check required approvals
        uses: Weetbix/configurable-required-approvals@v1.0.6
        with:
          requirements: |
            - patterns:
                - "/src/**/*"
              requiredApprovals: 3
          github-token: ${{ secrets.APPROVAL_GITHUB_TOKEN }}
