name: Approval Checks for Playground
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-approvals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check required approvals
        uses: weetbix/required-approvals-action@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          requirements: |
            - patterns:
                - "src/**/*"
              requiredApprovals: 2
